### ISSUE TITLE
Just categorical columns

### ISSUE THREAD

**Issue by rwcitek** [MLUISG/Functions#1]
In [Just_the_Functions]( https://github.com/MLUISG/Functions/blob/main/Just_the_Functions.ipynb ) ...

The  `all_the_value_counts()` function iterates over all columns.  This should probably be restricted to only those columns that are categorical.  Of course, the challenge is identifying categorical columns as they can be represented as both numerical and object data types.

**Comment by MLUISG** [comment]
I didn't think about narrowing it. Thanks for the feedback, I'm gonna try and make it only look for categorical info. I just wrote an impute function that can help with that.

**Comment by MLUISG** [comment]
I made a new function just for categorical data.
